import { ArrowUpRight, Bookmark, CheckCircle2, Clock3, MapPin, IndianRupee, Zap } from 'lucide-react';
import { Link } from 'wouter';
import type { Opportunity } from '@workspace/api-client-react';

export function OpportunityCard({ opportunity, onSave, compact = false }: { opportunity: Opportunity; onSave?: (value: boolean) => void; compact?: boolean }) {
  const o = opportunity;
  return <article data-testid={`card-opportunity-${o.id}`} className={`group relative rounded-2xl border border-border bg-card p-5 shadow-[var(--shadow-sm)] transition-all duration-300 hover:-translate-y-0.5 hover:border-primary/35 hover:shadow-[var(--shadow-md)] ${compact ? '' : 'sm:p-6'}`}>
    <div className="flex items-start gap-4"><div className="grid h-11 w-11 shrink-0 place-items-center rounded-xl bg-[#e7e4d9] font-display text-lg font-bold text-foreground">{o.company.slice(0, 1)}</div><div className="min-w-0 flex-1"><div className="flex items-start justify-between gap-2"><div><h3 className="font-display text-[16px] font-bold leading-snug">{o.role}</h3><p className="mt-0.5 text-sm text-muted-foreground">{o.company}</p></div><button data-testid={`button-save-opportunity-${o.id}`} onClick={() => onSave?.(!o.saved)} className={`rounded-lg p-2 transition ${o.saved ? 'bg-accent text-foreground' : 'text-muted-foreground hover:bg-muted hover:text-foreground'}`} aria-label={o.saved ? 'Unsave opportunity' : 'Save opportunity'}><Bookmark size={16} fill={o.saved ? 'currentColor' : 'none'} /></button></div></div></div>
    <div className="mt-5 flex flex-wrap gap-x-4 gap-y-2 text-xs text-muted-foreground"><span className="inline-flex items-center gap-1.5"><MapPin size={13} />{o.location}</span><span className="inline-flex items-center gap-1.5"><Zap size={13} />{o.mode}</span><span className="inline-flex items-center gap-1.5"><IndianRupee size={13} />{o.stipend || 'Stipend disclosed'}</span></div>
    <div className="mt-5 flex flex-wrap gap-1.5">{o.skills.slice(0, compact ? 3 : 4).map((skill) => <span key={skill} className="rounded-md bg-muted px-2 py-1 font-mono-app text-[10px] text-muted-foreground">{skill}</span>)}</div>
    <div className="mt-5 flex items-center justify-between border-t border-border/70 pt-4"><div className="flex items-center gap-2">{o.verified && <span className="inline-flex items-center gap-1 font-mono-app text-[10px] uppercase tracking-wide text-[#398560]"><CheckCircle2 size={13} /> verified</span>}<span className="inline-flex items-center gap-1 text-[11px] text-muted-foreground"><Clock3 size={12} />{o.deadline}</span></div><div className="flex items-center gap-2"><span className="font-mono-app text-[11px] font-bold text-primary">{o.fitScore}% fit</span><Link href={`/opportunities?id=${o.id}`} data-testid={`link-opportunity-${o.id}`} className="grid h-7 w-7 place-items-center rounded-md bg-foreground text-background transition-transform group-hover:translate-x-0.5"><ArrowUpRight size={14} /></Link></div></div>
  </article>;
}