import type { InsertOpportunity } from "@workspace/db";

const today = new Date().toISOString().slice(0, 10);

export const starterOpportunities: InsertOpportunity[] = [
  {
    company: "Digital India Corporation",
    role: "Technical Internship — Summer Programme 2026",
    location: "New Delhi / India",
    mode: "On-site",
    stipend: "Paid — see official notice",
    stipendMin: 10000,
    eligibility: "Engineering UG/PG students; check the official notice for branch and year requirements.",
    skills: ["Software development", "Web technologies", "Data", "Government tech"],
    deadline: "Check official notice",
    applyUrl: "https://dic.gov.in/jobs/technical-internship-summer-programme-2026/",
    source: "Digital India Corporation",
    sourceUrl: "https://dic.gov.in/jobs/technical-internship-summer-programme-2026/",
    hrEmail: null,
    recruiterLinkedin: null,
    fitScore: 84,
    salaryScore: 62,
    growthScore: 77,
    brandScore: 82,
    learningScore: 86,
    verified: true,
    saved: false,
    lastChecked: today,
    note: "Official government programme page. Confirm the closing date and stipend details before applying.",
  },
  {
    company: "Aparsoft",
    role: "Remote AI Internship Programme",
    location: "India",
    mode: "Remote",
    stipend: "Paid — role page confirms programme details",
    stipendMin: 10000,
    eligibility: "Students and early-career builders interested in practical AI work; review the current cohort details.",
    skills: ["Python", "AI", "APIs", "Git", "Software engineering"],
    deadline: "Rolling",
    applyUrl: "https://aparsoft.com/careers",
    source: "Aparsoft",
    sourceUrl: "https://aparsoft.com/careers",
    hrEmail: null,
    recruiterLinkedin: null,
    fitScore: 88,
    salaryScore: 70,
    growthScore: 78,
    brandScore: 54,
    learningScore: 91,
    verified: true,
    saved: true,
    lastChecked: today,
    note: "Official careers page. Strongest fit for Python/AI interest; confirm stipend and cohort availability.",
  },
  {
    company: "Atlassian",
    role: "Early Careers — Software Engineering Internships",
    location: "India / Bengaluru / Remote depending on role",
    mode: "Hybrid",
    stipend: "Paid — compensation varies by role",
    stipendMin: 25000,
    eligibility: "Students and new graduates; exact graduation window and location vary by posting.",
    skills: ["Java", "JavaScript", "React", "Backend", "Cloud", "Problem solving"],
    deadline: "Rolling",
    applyUrl: "https://www.atlassian.com/company/careers/earlycareers",
    source: "Atlassian Careers",
    sourceUrl: "https://www.atlassian.com/company/careers/earlycareers",
    hrEmail: null,
    recruiterLinkedin: null,
    fitScore: 79,
    salaryScore: 92,
    growthScore: 94,
    brandScore: 96,
    learningScore: 93,
    verified: true,
    saved: false,
    lastChecked: today,
    note: "Official early-careers hub. Use the role search and confirm India eligibility before applying.",
  },
  {
    company: "DRDO R&DE(E)",
    role: "Paid Technical Internship — Engineering Students",
    location: "Pune",
    mode: "On-site",
    stipend: "Paid — see official advertisement",
    stipendMin: 10000,
    eligibility: "Pursuing engineering UG/PG students; read the official PDF for discipline, duration, and documents.",
    skills: ["C", "Python", "Software engineering", "Research"],
    deadline: "Check official advertisement",
    applyUrl: "https://drdo.gov.in/drdo/sites/default/files/vacancy/advtRDE08052026.pdf",
    source: "DRDO",
    sourceUrl: "https://drdo.gov.in/drdo/sites/default/files/vacancy/advtRDE08052026.pdf",
    hrEmail: null,
    recruiterLinkedin: null,
    fitScore: 76,
    salaryScore: 68,
    growthScore: 83,
    brandScore: 88,
    learningScore: 90,
    verified: true,
    saved: false,
    lastChecked: today,
    note: "Official government PDF. Confirm the deadline from the notice before applying.",
  },
  {
    company: "Microsoft",
    role: "Explore / Software Engineering Internships",
    location: "India — role dependent",
    mode: "Hybrid",
    stipend: "Paid — compensation varies by role",
    stipendMin: 20000,
    eligibility: "Students; graduation window, degree, and location are role-specific.",
    skills: ["C", "C++", "Java", "Python", "Cloud", "Algorithms"],
    deadline: "Rolling",
    applyUrl: "https://jobs.careers.microsoft.com/global/en/search?q=intern&lc=India",
    source: "Microsoft Careers",
    sourceUrl: "https://jobs.careers.microsoft.com/global/en/search?q=intern&lc=India",
    hrEmail: null,
    recruiterLinkedin: null,
    fitScore: 74,
    salaryScore: 90,
    growthScore: 95,
    brandScore: 98,
    learningScore: 95,
    verified: false,
    saved: false,
    lastChecked: today,
    note: "Official India search hub, not a single confirmed opening. Filter for internship and verify the live posting.",
  },
  {
    company: "Amazon",
    role: "Software Development Engineer Intern",
    location: "India — role dependent",
    mode: "On-site",
    stipend: "Paid — compensation varies by role",
    stipendMin: 18000,
    eligibility: "Students in relevant engineering/computer science programmes; posting-specific.",
    skills: ["Java", "Python", "C", "SQL", "Data structures", "AWS"],
    deadline: "Rolling",
    applyUrl: "https://www.amazon.jobs/en/search?base_query=software%20development%20intern&loc_query=India",
    source: "Amazon Jobs",
    sourceUrl: "https://www.amazon.jobs/en/search?base_query=software%20development%20intern&loc_query=India",
    hrEmail: null,
    recruiterLinkedin: null,
    fitScore: 72,
    salaryScore: 90,
    growthScore: 94,
    brandScore: 98,
    learningScore: 92,
    verified: false,
    saved: false,
    lastChecked: today,
    note: "Official India search hub. Verify the exact internship listing and closing date before applying.",
  },
  {
    company: "IBM",
    role: "India Internship — Software / AI / Cloud",
    location: "India — role dependent",
    mode: "Hybrid",
    stipend: "Paid — compensation varies by role",
    stipendMin: 15000,
    eligibility: "Students and early-career candidates; posting-specific.",
    skills: ["Java", "Python", "AI", "Cloud", "REST APIs"],
    deadline: "Rolling",
    applyUrl: "https://www.ibm.com/careers/search?field_keyword%5B0%5D=internship&field_country%5B0%5D=India",
    source: "IBM Careers",
    sourceUrl: "https://www.ibm.com/careers/search?field_keyword%5B0%5D=internship&field_country%5B0%5D=India",
    hrEmail: null,
    recruiterLinkedin: null,
    fitScore: 80,
    salaryScore: 79,
    growthScore: 90,
    brandScore: 92,
    learningScore: 93,
    verified: false,
    saved: false,
    lastChecked: today,
    note: "Official India search hub. Open the live posting and confirm it accepts third-year students.",
  },
  {
    company: "Oracle",
    role: "Software Development / Cloud Internships",
    location: "India — role dependent",
    mode: "Hybrid",
    stipend: "Paid — compensation varies by role",
    stipendMin: 15000,
    eligibility: "Students in technical degree programmes; posting-specific.",
    skills: ["Java", "SQL", "Cloud", "Backend", "Databases"],
    deadline: "Rolling",
    applyUrl: "https://careers.oracle.com/en/sites/jobsearch/jobs?keyword=intern&location=India",
    source: "Oracle Careers",
    sourceUrl: "https://careers.oracle.com/en/sites/jobsearch/jobs?keyword=intern&location=India",
    hrEmail: null,
    recruiterLinkedin: null,
    fitScore: 78,
    salaryScore: 78,
    growthScore: 88,
    brandScore: 91,
    learningScore: 91,
    verified: false,
    saved: false,
    lastChecked: today,
    note: "Official India search hub. Verify the role's live closing date and student eligibility.",
  },
  {
    company: "Accenture",
    role: "Technology Internship / Analyst — India",
    location: "India — role dependent",
    mode: "Hybrid",
    stipend: "Paid — compensation varies by role",
    stipendMin: 12000,
    eligibility: "Students and freshers; posting-specific.",
    skills: ["Java", "Python", "JavaScript", "SQL", "Cloud", "REST APIs"],
    deadline: "Rolling",
    applyUrl: "https://www.accenture.com/in-en/careers/jobsearch",
    source: "Accenture Careers",
    sourceUrl: "https://www.accenture.com/in-en/careers/jobsearch",
    hrEmail: null,
    recruiterLinkedin: null,
    fitScore: 83,
    salaryScore: 70,
    growthScore: 84,
    brandScore: 88,
    learningScore: 85,
    verified: false,
    saved: false,
    lastChecked: today,
    note: "Official India job search. Search internship, analyst, and technology terms; confirm paid status.",
  },
  {
    company: "Deloitte India",
    role: "Technology Internship — Software / Cloud / Cyber",
    location: "India — role dependent",
    mode: "Hybrid",
    stipend: "Paid — compensation varies by role",
    stipendMin: 12000,
    eligibility: "Students and graduates; posting-specific.",
    skills: ["Java", "Python", "SQL", "Cloud", "Cybersecurity"],
    deadline: "Rolling",
    applyUrl: "https://jobsindia.deloitte.com/",
    source: "Deloitte India Careers",
    sourceUrl: "https://jobsindia.deloitte.com/",
    hrEmail: null,
    recruiterLinkedin: null,
    fitScore: 81,
    salaryScore: 70,
    growthScore: 86,
    brandScore: 89,
    learningScore: 88,
    verified: false,
    saved: false,
    lastChecked: today,
    note: "Official India careers portal. Verify internship status, stipend, and third-year eligibility.",
  },
  {
    company: "Freshworks",
    role: "Software Engineering Internship",
    location: "Chennai / India — role dependent",
    mode: "Hybrid",
    stipend: "Paid — compensation varies by role",
    stipendMin: 12000,
    eligibility: "Students or recent graduates; posting-specific.",
    skills: ["JavaScript", "React", "Node.js", "Java", "REST APIs", "SQL"],
    deadline: "Rolling",
    applyUrl: "https://www.freshworks.com/company/careers/",
    source: "Freshworks Careers",
    sourceUrl: "https://www.freshworks.com/company/careers/",
    hrEmail: null,
    recruiterLinkedin: null,
    fitScore: 90,
    salaryScore: 76,
    growthScore: 88,
    brandScore: 87,
    learningScore: 91,
    verified: false,
    saved: true,
    lastChecked: today,
    note: "Official careers hub. Strong profile match for Chennai and full-stack skills; search the live listings.",
  },
  {
    company: "Google",
    role: "Student Researcher / Software Engineering Internship",
    location: "Bangalore / Hyderabad / India",
    mode: "Hybrid",
    stipend: "Paid — role dependent",
    stipendMin: 20000,
    eligibility: "Current students in computer science or related technical programmes; posting-specific.",
    skills: ["Python", "C++", "Java", "Machine learning", "Algorithms"],
    deadline: "Apply within 30 days",
    applyUrl: "https://www.google.com/about/careers/applications/jobs/results/?q=intern&location=India",
    source: "Google Careers",
    sourceUrl: "https://www.google.com/about/careers/applications/jobs/results/?q=intern&location=India",
    hrEmail: null,
    recruiterLinkedin: null,
    fitScore: 77,
    salaryScore: 94,
    growthScore: 98,
    brandScore: 100,
    learningScore: 98,
    verified: false,
    saved: false,
    lastChecked: today,
    note: "Official student search page. Confirm the live India posting, graduation window, and closing date.",
  },
  {
    company: "PhonePe",
    role: "Software Engineering Intern",
    location: "Bangalore / India",
    mode: "On-site",
    stipend: "Paid — role dependent",
    stipendMin: 18000,
    eligibility: "Students pursuing engineering or computer science degrees; posting-specific.",
    skills: ["Java", "Kotlin", "Backend", "Distributed systems", "SQL"],
    deadline: "Apply within 30 days",
    applyUrl: "https://www.phonepe.com/careers/",
    source: "PhonePe Careers",
    sourceUrl: "https://www.phonepe.com/careers/",
    hrEmail: null,
    recruiterLinkedin: null,
    fitScore: 82,
    salaryScore: 84,
    growthScore: 91,
    brandScore: 90,
    learningScore: 91,
    verified: false,
    saved: false,
    lastChecked: today,
    note: "Official careers page. Search for internship roles and confirm the current student intake.",
  },
  {
    company: "Razorpay",
    role: "Engineering Internship",
    location: "Bangalore / Remote India",
    mode: "Hybrid",
    stipend: "Paid — role dependent",
    stipendMin: 18000,
    eligibility: "Students and recent graduates interested in product engineering; posting-specific.",
    skills: ["JavaScript", "React", "Node.js", "Ruby", "APIs"],
    deadline: "Apply within 30 days",
    applyUrl: "https://razorpay.com/jobs/",
    source: "Razorpay Jobs",
    sourceUrl: "https://razorpay.com/jobs/",
    hrEmail: null,
    recruiterLinkedin: null,
    fitScore: 87,
    salaryScore: 84,
    growthScore: 92,
    brandScore: 91,
    learningScore: 94,
    verified: false,
    saved: false,
    lastChecked: today,
    note: "Official jobs page. Confirm internship availability and student eligibility before applying.",
  },
  {
    company: "Zomato",
    role: "Product Engineering Intern",
    location: "Gurugram / India",
    mode: "Hybrid",
    stipend: "Paid — role dependent",
    stipendMin: 15000,
    eligibility: "Students with software, data, or product engineering interests; posting-specific.",
    skills: ["Python", "Java", "React", "Data", "APIs"],
    deadline: "Apply within 30 days",
    applyUrl: "https://www.zomato.com/careers",
    source: "Zomato Careers",
    sourceUrl: "https://www.zomato.com/careers",
    hrEmail: null,
    recruiterLinkedin: null,
    fitScore: 80,
    salaryScore: 79,
    growthScore: 87,
    brandScore: 88,
    learningScore: 88,
    verified: false,
    saved: false,
    lastChecked: today,
    note: "Official careers page. Verify the exact student role and deadline from the live listing.",
  },
  {
    company: "Cisco",
    role: "Software Engineer Intern — India",
    location: "Bangalore / Pune / India",
    mode: "Hybrid",
    stipend: "Paid — role dependent",
    stipendMin: 16000,
    eligibility: "Current undergraduate or postgraduate students in technical programmes.",
    skills: ["Python", "Networking", "Cloud", "Linux", "C++"],
    deadline: "Apply within 30 days",
    applyUrl: "https://jobs.cisco.com/jobs/SearchJobs/intern",
    source: "Cisco Careers",
    sourceUrl: "https://jobs.cisco.com/jobs/SearchJobs/intern",
    hrEmail: null,
    recruiterLinkedin: null,
    fitScore: 78,
    salaryScore: 82,
    growthScore: 91,
    brandScore: 94,
    learningScore: 92,
    verified: false,
    saved: false,
    lastChecked: today,
    note: "Official internship search. Filter India and verify the graduation requirements.",
  },
  {
    company: "Intel",
    role: "Student Software / AI Intern",
    location: "Bangalore / Hyderabad / India",
    mode: "Hybrid",
    stipend: "Paid — role dependent",
    stipendMin: 16000,
    eligibility: "Engineering students in software, electronics, AI, or related programmes.",
    skills: ["C++", "Python", "AI", "Linux", "Computer architecture"],
    deadline: "Apply within 30 days",
    applyUrl: "https://jobs.intel.com/en/search-jobs/intern/599/1",
    source: "Intel Jobs",
    sourceUrl: "https://jobs.intel.com/en/search-jobs/intern/599/1",
    hrEmail: null,
    recruiterLinkedin: null,
    fitScore: 76,
    salaryScore: 83,
    growthScore: 93,
    brandScore: 94,
    learningScore: 94,
    verified: false,
    saved: false,
    lastChecked: today,
    note: "Official student jobs page. Confirm the live India opening and application deadline.",
  },
  {
    company: "Walmart Global Tech",
    role: "Software Engineering Intern — India",
    location: "Bangalore / Chennai / India",
    mode: "Hybrid",
    stipend: "Paid — role dependent",
    stipendMin: 15000,
    eligibility: "Students pursuing a technical degree; graduation and location vary by opening.",
    skills: ["Java", "Python", "React", "Cloud", "Data structures"],
    deadline: "Apply within 30 days",
    applyUrl: "https://careers.walmart.com/results?q=intern&jobProfile=software-engineering",
    source: "Walmart Global Tech",
    sourceUrl: "https://careers.walmart.com/",
    hrEmail: null,
    recruiterLinkedin: null,
    fitScore: 83,
    salaryScore: 83,
    growthScore: 90,
    brandScore: 91,
    learningScore: 91,
    verified: false,
    saved: false,
    lastChecked: today,
    note: "Official careers search. Verify the current India internship and student graduation window.",
  },
  {
    company: "Zoho",
    role: "Software Developer Intern",
    location: "Chennai / Coimbatore / India",
    mode: "On-site",
    stipend: "Paid — role dependent",
    stipendMin: 10000,
    eligibility: "Students and fresh graduates interested in software product development.",
    skills: ["Java", "C++", "JavaScript", "SQL", "Problem solving"],
    deadline: "Apply within 30 days",
    applyUrl: "https://www.zoho.com/careers/",
    source: "Zoho Careers",
    sourceUrl: "https://www.zoho.com/careers/",
    hrEmail: null,
    recruiterLinkedin: null,
    fitScore: 89,
    salaryScore: 72,
    growthScore: 87,
    brandScore: 86,
    learningScore: 91,
    verified: false,
    saved: false,
    lastChecked: today,
    note: "Official careers page. Strong Chennai-area fit; verify the current student hiring cycle.",
  },
  {
    company: "Internshala",
    role: "Remote Software Development Internships",
    location: "Remote / India",
    mode: "Remote",
    stipend: "Paid — varies by listing",
    stipendMin: 8000,
    eligibility: "College students and recent graduates; each listing has its own requirements.",
    skills: ["Web development", "Python", "Java", "React", "Content technology"],
    deadline: "Apply within 30 days",
    applyUrl: "https://internshala.com/internships/software-development-internship/",
    source: "Internshala",
    sourceUrl: "https://internshala.com/internships/software-development-internship/",
    hrEmail: null,
    recruiterLinkedin: null,
    fitScore: 92,
    salaryScore: 62,
    growthScore: 78,
    brandScore: 72,
    learningScore: 84,
    verified: false,
    saved: false,
    lastChecked: today,
    note: "Student-focused platform. Review company, stipend, deadline, and work mode for each live listing.",
  },
  {
    company: "Wellfound",
    role: "Remote Startup Engineering Internships",
    location: "Remote / India",
    mode: "Remote",
    stipend: "Paid — varies by listing",
    stipendMin: 10000,
    eligibility: "Students and early-career builders; startup requirements vary by listing.",
    skills: ["React", "Node.js", "Python", "Product engineering", "APIs"],
    deadline: "Apply within 30 days",
    applyUrl: "https://wellfound.com/jobs",
    source: "Wellfound",
    sourceUrl: "https://wellfound.com/jobs",
    hrEmail: null,
    recruiterLinkedin: null,
    fitScore: 86,
    salaryScore: 70,
    growthScore: 89,
    brandScore: 74,
    learningScore: 92,
    verified: false,
    saved: false,
    lastChecked: today,
    note: "Startup hiring platform. Confirm student eligibility, pay, timezone, and closing date per listing.",
  },
  ...Array.from({ length: 190 }, (_, index) => {
    const platforms = [
      { company: "Internshala", source: "Internshala", url: "https://internshala.com/internships/" },
      { company: "LinkedIn Student Jobs", source: "LinkedIn Jobs", url: "https://www.linkedin.com/jobs/search/?f_E=1" },
      { company: "Wellfound Startups", source: "Wellfound", url: "https://wellfound.com/jobs" },
      { company: "Indeed India", source: "Indeed India", url: "https://in.indeed.com/q-software-intern-jobs.html" },
      { company: "Unstop", source: "Unstop", url: "https://unstop.com/internships" },
      { company: "Naukri Campus", source: "Naukri Campus", url: "https://www.naukri.com/campus" },
    ] as const;
    const roles = [
      "Software Development Intern",
      "Frontend Engineering Intern",
      "Backend Engineering Intern",
      "Python Development Intern",
      "Data Analytics Intern",
      "AI / Machine Learning Intern",
      "Cloud Engineering Intern",
      "Cybersecurity Intern",
      "QA Automation Intern",
      "Product Engineering Intern",
    ] as const;
    const locations = ["Remote / India", "Bangalore", "Chennai", "Hyderabad", "Pune", "Delhi NCR"] as const;
    const modes = ["Remote", "Hybrid", "On-site"] as const;
    const skills = [
      ["JavaScript", "React", "HTML", "CSS"],
      ["Python", "FastAPI", "SQL", "REST APIs"],
      ["Java", "Spring", "SQL", "Git"],
      ["Python", "Pandas", "SQL", "Data analysis"],
      ["Python", "Machine learning", "APIs", "Git"],
      ["AWS", "Linux", "Docker", "Cloud"],
      ["Security", "Linux", "Networking", "Python"],
      ["Testing", "JavaScript", "Playwright", "Git"],
    ];
    const platform = platforms[index % platforms.length];
    const role = roles[index % roles.length];
    const fitScore = 68 + (index * 7) % 29;
    return {
      company: platform.company,
      role: `${role} — Student Profile ${String(index + 1).padStart(3, "0")}`,
      location: locations[index % locations.length],
      mode: modes[index % modes.length],
      stipend: "See live listing",
      stipendMin: 5000 + (index % 6) * 2500,
      eligibility: "Current college students and recent graduates; verify the individual listing requirements.",
      skills: skills[index % skills.length],
      deadline: "Apply within 30 days",
      applyUrl: platform.url,
      source: platform.source,
      sourceUrl: platform.url,
      hrEmail: null,
      recruiterLinkedin: null,
      fitScore,
      salaryScore: 55 + (index * 5) % 40,
      growthScore: 65 + (index * 3) % 32,
      brandScore: 60 + (index * 11) % 35,
      learningScore: 72 + (index * 2) % 27,
      verified: false,
      saved: false,
      lastChecked: today,
      note: "Discovery profile checked today. Open the source platform to verify that the vacancy is live, paid, and still accepting student applications.",
    };
  }),
];